### ISSUE TITLE
Where is TIMS project?

### ISSUE THREAD

**Issue by llasha** [SmarterApp/TIMS_Test#3]
Hello,
Where could I find the TIMS project and the related up-to-date information about the local development and/or deployment on AWS?
I have noticed that all AP projects now are archived and read only. As for the installation docu found on SmarterApp.org website, it seems pretty much outdated or obsolete.
Thank you in advance for your time and a reply.

**Comment by alexdean201** [comment]
Thanks for your question and observation. The TIMS project has been moved to be a private Smarter Balanced repository. The documentation on SmarterApp will also be undergoing updates where outdated material will be removed.

I do not recognize your GitHub username. Are you with an assessment vendor, or Smarter Balanced consortium member?

**Comment by llasha** [comment]
Thanks for your reply and the information regarding the TIMS project. I just saw few references to the project in several README.md files in AP_ repos, so I was wondering where to find it.

No, I am not. Otherwise, I would not inquire about the project here.
